### ISSUE TITLE
Create Refferrer modals when accessing this page from saving-satoshi-main

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi-script#1]
We want to have some modals pop up when accessing this page from chapter 10 in saving satoshi

**Comment by GBKS** [comment]
I started tinkering with this a little bit and have some rough ideas and questions.

Generally, I think it would be great to keep the info sidebar. For general use, it could allow you to try out some examples with pre-populated scripts, and provide other helpful info and links. For Saving Satoshi use, it could provide a super brief summary of what to achieve. Makes it a little easier for the user when the site connects to what they are doing.

I'm also wondering about what happens when the user wants to now port the script and other input back to Saving Satoshi. Can we offer a link back, which includes the input as query parameters? Or do we need copy and paste buttons respectively?

![image](https://github.com/user-attachments/assets/02a938eb-6e53-44e4-b215-819e04c7716d)

**Comment by benalleng** [comment]
I think we need a button like copy script. I have added it at the moment in place of the next button by the success bar.  If they already have some progress on the main saving satoshi page linking back will reset it even if we have a referrer link to add the script they just completed. so a copy button is really needed here

**Comment by benalleng** [comment]
created the commit for this and how to use it explained in #3
